### ISSUE TITLE
[windows] plugin fallbackfonts. Error "Expected version 3.5.0"

### ISSUE THREAD

**Issue by maksimaliabyshev** [pragtical/plugins#17]
` ppm reinstall --verbose fallbackfonts` - Installed version 0.1

launch pragtical
![image](https://github.com/user-attachments/assets/ee5be59f-d3c3-4553-a8b7-f01787fc2d12)

`ppm reinstall --verbose fallbackfonts:3.5.0`

src/ppm.lua:1875: can't find addon fallbackfonts mod-version: 3.4.0

**Comment by jgmdev** [comment]
That plugin was a remnant of the original lite-plugins repository, pragtical already provides fallback fonts support as part of the core so removed this plugin which is for lite only.

To see how to configure a font follow: https://pragtical.dev/docs/user-guide/configuration#fonts

Thanks for reporting!
