### ISSUE TITLE
[windows] plugin link_opener. Error - no opens URL.

### ISSUE THREAD

**Issue by maksimaliabyshev** [pragtical/plugins#18]
in cmd console run `start https://google.com` - open site in default browser

in pragtical ctrl+enter on link url - open cmd console
![image](https://github.com/user-attachments/assets/b25dad4f-84e2-48b3-8722-bbf276b00d9e)

**Comment by jgmdev** [comment]
Seems that using double quotes with an url doesn't works for start. Should be reported on the plugin repository https://github.com/irisdominguez/pragtical_link-opener_plugin

For the moment you can fix it locally by replacing on the plugin init.lua file the following:

```diff
-    os.execute(string.format('%s "%s"', config.plugins.link_opener.filelauncher, url))
+    os.execute(string.format('%s %s', config.plugins.link_opener.filelauncher, url))
```

**Comment by irisdominguez** [comment]
Fixed on my side, and took the opportunity to add a bit of needed functionality. Do I have to do anything to update the version in here?

**Comment by maksimaliabyshev** [comment]
@irisdominguez  Checked the updated version, now it works correctly, but sometimes cmd.exe window appears for a fraction of a second, but it's nothing, the main thing is that it works.

As far as I know, you don't need to do anything else, the plugin repository maintainers update their own set of plugins.
