### ISSUE TITLE
formatters plugin

### ISSUE THREAD

**Issue by kmafeni04** [pragtical/plugins#2]
Wrote a couple formatters for typescript and shell script and wanted to share them, checked the formatters page and seen that the maintainer isn't active or responding to pull requests there. I've never contributed to a project so I'm not even sure how this goes but wanted to ask for any assistance

**Comment by kmafeni04** [comment]
Also discovered some issues with it after you change the project folder when the formatter doesn't work 

The log:

Tue Sep 26 00:38:18 2023 [ERROR] /home/kome/.config/pragtical/plugins/formatter.lua:64: attempt to concatenate local 'filename' (a nil value) at /usr/share/pragtical/core/init.lua:1069

stack traceback:
/home/kome/.config/pragtical/plugins/formatter.lua:64: in function 'perform'
/usr/share/pragtical/core/command.lua:144: in function </usr/share/pragtical/core/command.lua:137>
[C]: in function 'xpcall'
/usr/share/pragtical/core/init.lua:1068: in function 'try'
/usr/share/pragtical/core/command.lua:169: in function 'perform'
/usr/share/pragtical/core/keymap.lua:230: in function 'on_key_pressed'
/usr/share/pragtical/core/init.lua:1086: in function 'on_event'
/usr/share/pragtical/plugins/macro.lua:19: in function </usr/share/pragtical/plugins/macro.lua:18>
[C]: in function 'xpcall'
/usr/share/pragtical/core/init.lua:1068: in function 'try'
/usr/share/pragtical/core/init.lua:1178: in function 'step'
/usr/share/pragtical/core/init.lua:1301: in function 'core_run'
/usr/share/pragtical/plugins/settings.lua:1914: in function 'core_run'
/usr/share/pragtical/plugins/ipc.lua:852: in function 'core_run'
/home/kome/.config/pragtical/plugins/recentfiles.lua:77: in function 'run'
[string "local core..."]:15: in function <[string "local core..."]:6>
[C]: in function 'xpcall'
[string "local core..."]:6: in main chunk

**Comment by jgmdev** [comment]
Do you mean this plugin https://github.com/vincens2005/lite-formatters ? We may need our own formatters fork in order to adapt the code for the new project api changes. You could then submit pull requests to our fork.

**Comment by kmafeni04** [comment]
> Do you mean this plugin https://github.com/vincens2005/lite-formatters ? We may need our own formatters fork in order to adapt the code for the new project api changes. You could then submit pull requests to our fork.

Yes, that's the plugin. Alright then, I'll wait

**Comment by jgmdev** [comment]
> Yes, that's the plugin. Alright then, I'll wait

Sorry for the delay, I was able today to fork the repo to https://github.com/pragtical/formatters and to fix the code to make it work with Pragtical and even newer Lite XL releases. Feel free to send any PR's to it, I also plan to make some changes to that plugin to support the Settings UI and automatically enable language formatters if their binaries are automatically found on startup.

**Comment by jgmdev** [comment]
Did some refactoring to our [formatter plugin](https://github.com/pragtical/formatter) fork as allowing formatters to automatically get registered, checking if the binaries are installed on the system before trying to run the formatter and added settings ui support to be able to customize the formatter binary path, arguments and enable/disable it.

Will not work with old non namespaced config values like `config.format_on_save` and instead one would need to use `config.plugins.formatter.format_on_save` .  It still allows customizing a formatter arguments but with the same config treatement. More details on the updated README file of the plugin.

**Comment by kmafeni04** [comment]
Will take a look soon

**Comment by kmafeni04** [comment]
Works pretty nicely for my minimal testing, have to play around with creating new formatters for different languages now
